### ISSUE TITLE
please how to build from source

### ISSUE THREAD

**Issue by JanuszChmiel** [yggdrasil-sr/yggdrasil-prototype#2]
dear MR drasil,
I Am visually impaired advanced user and I would like to try The latest bleeding edge code of yours screen reader. I AM triing to build it by using cargo build
command. But unfortunately, build process fails due to bad reference to at-spi library.

atspi={git="https://github.com/yggdrasil-sr/atspi-rs.git"}

I have decided to try this ammazing project, because you have chosen ammazing programming language which support very professional memory management and allow to produce fast machine code.
I have found out, that building projects based on Cargo or Rust can be very painful adventure thanks to libraryes issues. I had very painful adventure when I have tried to build Shortwave Internet radio player. May be, that yours instructions would show Me, thsat Rust can be A friendly language and Especially Cargo build system too.
Thank you very much for yours instructions.
With kindness regards and with The deepest possible appreciation to yours programmers work.
Janusz Chmiel

**Comment by TheQuinbox** [comment]
Not on Linux at the second so can't try and build to tell you what needs done, but you can just grab a release from [here](https://github.com/yggdrasil-sr/yggdrasil-prototype/releases/download/v-0.4.20/yggdrasil-prototype.run)

**Comment by TTWNO** [comment]
If you're on an Arch-based distrobution, you can try what we have now (which is not much), by installing the `yggdrasil-sr` AUR package.

**Comment by JanuszChmiel** [comment]
Oh thank you for yours wonderful access to Me. I will try to run yours precompiled release and I will also try to update by using AUR ArchLinux community.
I have even tried to use Linux apps on Android phone by using special complex Bash scripts from MR Rausty. So I can even experiment by using VNC protocol and Android phone, which is very portable. And yours C app could even run much more faster even on A phone than Orca.
I will do it a try tomorrow. Thanks to Proot and thanks to BVNC clients apps for Android it is really possible to run many Linux apps. The speed mostly depend on The Android kernel drivers and Binary services for controlling sound.
Thank you very much for yours time and kind access to Me.

**Comment by mcb2003** [comment]
Closing this for now, Yggdrasil really isn't ready to be used for anything yet, and the issue @JanuszChmiel had with atspi-rs will no longer exist, since we're not using that any more.
